plugins { id 'com.android.application' }

android {
    namespace 'fr.permsmp.afkgodnode'
    compileSdk 36

    defaultConfig {
        applicationId 'fr.permsmp.afkgodnode'
        minSdk 26
        targetSdk 36
        versionCode 130
        versionName '1.3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
