cmake_minimum_required(VERSION 3.22.1)
project(autosub_native)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_SERVER OFF CACHE BOOL "" FORCE)
add_subdirectory(whisper.cpp whisper-build)
add_library(autosub_native SHARED native.cpp)
target_include_directories(autosub_native PRIVATE whisper.cpp/include)
target_link_libraries(autosub_native whisper log android)
