package com.neo.tracepilot;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public final class MainActivity extends Activity{
 static final int REQ_LOC=7001;TraceDb db;FrameLayout content;LinearLayout nav;String page="Live";long day;boolean raw;
 Handler h=new Handler(Looper.getMainLooper());Runnable tick=new Runnable(){public void run(){try{if("Live".equals(page))show("Live");}catch(Throwable ignored){}h.postDelayed(this,3000);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new TraceDb(this);day=dayStart(System.currentTimeMillis());shell();show("Live");h.postDelayed(tick,3000);}
 @Override protected void onDestroy(){h.removeCallbacksAndMessages(null);if(db!=null)db.close();super.onDestroy();}
 void shell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(0,Ui.dp(this,22),0,0);root.setBackgroundColor(Ui.BG);LinearLayout top=Ui.row(this);top.setPadding(Ui.dp(this,16),Ui.dp(this,12),Ui.dp(this,16),Ui.dp(this,10));LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);tt.addView(Ui.title(this,"TracePilot"));tt.addView(Ui.muted(this,"R7 Full Core • H24 • local-first"));top.addView(tt,Ui.weight(1));root.addView(top);content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=Ui.row(this);nav.setPadding(Ui.dp(this,8),Ui.dp(this,8),Ui.dp(this,8),Ui.dp(this,10));nav.setBackgroundColor(Ui.SURFACE);String[] ps={"Live","Carte","Timeline","Réglages"};for(final String p:ps){Button b=Ui.chip(this,p,false);b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){show(p);}});LinearLayout.LayoutParams lp=Ui.weight(1);lp.leftMargin=Ui.dp(this,3);lp.rightMargin=Ui.dp(this,3);nav.addView(b,lp);}root.addView(nav);setContentView(root);}
 void show(String p){page=p;content.removeAllViews();if("Live".equals(p))content.addView(live());else if("Carte".equals(p))content.addView(map());else if("Timeline".equals(p))content.addView(timeline());else content.addView(settings());for(int i=0;i<nav.getChildCount();i++){Button b=(Button)nav.getChildAt(i);boolean on=b.getText().toString().equals(p);b.setTextColor(on?Ui.BG:Ui.MUTED);b.setBackground(on?Ui.bg(this,Ui.CYAN,18):Ui.stroke(this,Ui.SURFACE,Ui.BORDER,18));}}
 LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(Ui.dp(this,14),Ui.dp(this,4),Ui.dp(this,14),Ui.dp(this,20));return l;}
 LinearLayout.LayoutParams cardLp(){LinearLayout.LayoutParams x=Ui.match();x.topMargin=Ui.dp(this,10);return x;}
 View pair(String k,String v,int color){LinearLayout r=Ui.row(this);r.setPadding(0,Ui.dp(this,5),0,Ui.dp(this,5));r.addView(Ui.muted(this,k),Ui.weight(1));TextView t=Ui.text(this,v,13,color,true);t.setGravity(Gravity.END);r.addView(t);return r;}
 ScrollView wrap(LinearLayout l){ScrollView s=new ScrollView(this);s.addView(l);return s;}

 View live(){LinearLayout l=col();boolean enabled=getSharedPreferences("tracepilot",MODE_PRIVATE).getBoolean("tracking_enabled",false);boolean net=Net.internet(this);TraceDb.Point p=db.last();boolean fix=p!=null&&System.currentTimeMillis()-p.ts<15000;LinearLayout state=Ui.card(this);state.addView(Ui.section(this,"ÉTAT RÉEL"));state.addView(Ui.gap(this,7));state.addView(pair("Internet",net?"Disponible":"Hors ligne",net?Ui.GREEN:Ui.YELLOW));state.addView(pair("GNSS",fix?"Fix récent":"Aucun fix récent",fix?Ui.GREEN:Ui.YELLOW));state.addView(pair("Satellites",db.getMeta("sats_used","0")+" / "+db.getMeta("sats_visible","0"),Ui.TEXT));state.addView(pair("Service H24",enabled?db.getMeta("service_state","démarrage"):"arrêté",enabled?Ui.GREEN:Ui.MUTED));l.addView(state,cardLp());
 LinearLayout tr=Ui.card(this);tr.addView(Ui.section(this,"SUIVI H24"));tr.addView(Ui.gap(this,7));tr.addView(Ui.muted(this,"GPS et capteurs fonctionnent sans Internet. Seuls le fond de carte et la reconstruction routière ont besoin d'Internet."));Button b=Ui.button(this,enabled?"Arrêter le suivi":"Démarrer le suivi H24",!enabled);b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){if(getSharedPreferences("tracepilot",MODE_PRIVATE).getBoolean("tracking_enabled",false))stopTrack();else requestStart();}});LinearLayout.LayoutParams bl=Ui.match();bl.topMargin=Ui.dp(this,10);tr.addView(b,bl);l.addView(tr,cardLp());
 if(p!=null){LinearLayout c=Ui.card(this);c.addView(Ui.section(this,"DERNIER POINT RAW"));c.addView(Ui.gap(this,7));c.addView(Ui.text(this,label(p.mode)+"  "+Math.round(p.confidence*100)+" %",22,Ui.modeColor(p.mode),true));c.addView(Ui.gap(this,6));c.addView(Ui.muted(this,date(p.ts)+" • "+time(p.ts)+" • "+String.format(Locale.ROOT,"%.5f, %.5f",p.lat,p.lon)));c.addView(pair("Vitesse",String.format(Locale.ROOT,"%.1f km/h",p.speed*3.6),Ui.TEXT));c.addView(pair("Précision",p.acc<0?"—":String.format(Locale.ROOT,"%.1f m",p.acc),Ui.TEXT));c.addView(pair("Altitude",String.format(Locale.ROOT,"%.0f m",p.alt),Ui.TEXT));c.addView(pair("Pression",Double.isNaN(p.pressure)?"—":String.format(Locale.ROOT,"%.1f hPa",p.pressure),Ui.TEXT));final TraceDb.Point fp=p;c.setOnClickListener(new View.OnClickListener(){public void onClick(View v){point(fp);}});l.addView(c,cardLp());}
 LinearLayout hist=Ui.card(this);hist.addView(Ui.section(this,"DONNÉES LOCALES"));hist.addView(Ui.gap(this,7));hist.addView(pair("Points RAW",String.valueOf(db.count()),Ui.TEXT));hist.addView(pair("Trous en attente",String.valueOf(db.pendingCount()),db.pendingCount()>0?Ui.YELLOW:Ui.GREEN));hist.addView(pair("Base SQLite",bytes(db.bytes(this)),Ui.TEXT));l.addView(hist,cardLp());return wrap(l);}

 View map(){LinearLayout l=col();long en=day+86400000L;List<TraceDb.Point> pts=db.points(day,en,2500);List<TraceDb.Gap> gs=db.gaps(day,en);LinearLayout c=Ui.card(this);c.addView(Ui.section(this,"TRAJECTOIRE LOCALE"));c.addView(Ui.gap(this,7));c.addView(Ui.muted(this,"Même hors ligne, les points et segments locaux restent visibles. Aucun fond de carte n'est stocké."));TraceView tv=new TraceView(this);tv.data(pts,gs);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,Ui.dp(this,300));vp.topMargin=Ui.dp(this,12);c.addView(tv,vp);l.addView(c,cardLp());LinearLayout m=Ui.card(this);m.addView(Ui.section(this,"FONDS ONLINE"));m.addView(Ui.gap(this,7));String[] n={"Carte","Satellite","Relief","Hybride"},st={"basic","satellite","relief","hybrid"};for(int i=0;i<n.length;i++){final String fs=st[i];Button x=Ui.button(this,n[i],i==0);x.setOnClickListener(new View.OnClickListener(){public void onClick(View v){Intent in=new Intent(MainActivity.this,MapActivity.class);in.putExtra("style",fs);in.putExtra("start",day);in.putExtra("end",day+86400000L);startActivity(in);}});LinearLayout.LayoutParams lp=Ui.match();lp.topMargin=i==0?0:Ui.dp(this,7);m.addView(x,lp);}l.addView(m,cardLp());return wrap(l);}

 View timeline(){LinearLayout l=col();LinearLayout head=Ui.card(this);head.addView(Ui.section(this,"TIMELINE"));head.addView(Ui.gap(this,7));Button d=Ui.button(this,date(day),false);d.setOnClickListener(new View.OnClickListener(){public void onClick(View v){pick();}});head.addView(d);LinearLayout togg=Ui.row(this);Button s=Ui.chip(this,"SMART",!raw),r=Ui.chip(this,"RAW",raw);s.setOnClickListener(new View.OnClickListener(){public void onClick(View v){raw=false;show("Timeline");}});r.setOnClickListener(new View.OnClickListener(){public void onClick(View v){raw=true;show("Timeline");}});togg.addView(s,Ui.weight(1));LinearLayout.LayoutParams rp=Ui.weight(1);rp.leftMargin=Ui.dp(this,8);togg.addView(r,rp);LinearLayout.LayoutParams tp=Ui.match();tp.topMargin=Ui.dp(this,9);head.addView(togg,tp);head.addView(Ui.gap(this,6));head.addView(Ui.muted(this,raw?"RAW = mesures réellement reçues, jamais réécrites.":"SMART = classification + trous reconstruits clairement marqués."));l.addView(head,cardLp());long en=day+86400000L;if(!raw){for(final TraceDb.Gap g:db.gaps(day,en)){LinearLayout x=Ui.card(this);x.addView(Ui.text(this,time(g.startTs)+" → "+time(g.endTs)+"  "+("reconstructed".equals(g.status)?label(g.mode):"À reconstruire"),14,"reconstructed".equals(g.status)?Ui.modeColor(g.mode):Ui.YELLOW,true));x.addView(Ui.gap(this,4));x.addView(Ui.muted(this,duration(g.endTs-g.startTs)+" • "+("reconstructed".equals(g.status)?Math.round(g.confidence*100)+" %":"attente Internet")));x.setOnClickListener(new View.OnClickListener(){public void onClick(View v){new AlertDialog.Builder(MainActivity.this).setTitle("Segment").setMessage(g.reason+"\n\nMode: "+label(g.mode)+"\nConfiance: "+Math.round(g.confidence*100)+" %").setPositiveButton("OK",null).show();}});l.addView(x,cardLp());}}
 List<TraceDb.Point> ps=db.pointsDesc(day,en,raw?1000:300);for(final TraceDb.Point p:ps){LinearLayout x=Ui.card(this);x.addView(Ui.text(this,time(p.ts)+"  "+label(p.mode)+(raw?"  RAW":"  "+Math.round(p.confidence*100)+" %"),14,raw?Ui.TEXT:Ui.modeColor(p.mode),true));x.addView(Ui.gap(this,4));x.addView(Ui.muted(this,String.format(Locale.ROOT,"%.5f, %.5f • %.1f km/h • ±%.0f m",p.lat,p.lon,p.speed*3.6,p.acc)));x.setOnClickListener(new View.OnClickListener(){public void onClick(View v){point(p);}});l.addView(x,cardLp());}if(ps.isEmpty())l.addView(Ui.muted(this,"Aucun point ce jour-là."),cardLp());return wrap(l);}

 View settings(){LinearLayout l=col();LinearLayout p=Ui.card(this);p.addView(Ui.section(this,"AUTORISATIONS"));p.addView(Ui.gap(this,7));p.addView(pair("Localisation précise",perm(Manifest.permission.ACCESS_FINE_LOCATION)?"accordée":"refusée",perm(Manifest.permission.ACCESS_FINE_LOCATION)?Ui.GREEN:Ui.RED));p.addView(pair("Batterie",battery()?"non optimisée":"optimisation active",battery()?Ui.GREEN:Ui.YELLOW));Button a=Ui.button(this,"Ouvrir les autorisations Android",false);a.setOnClickListener(new View.OnClickListener(){public void onClick(View v){startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}});LinearLayout.LayoutParams lp=Ui.match();lp.topMargin=Ui.dp(this,9);p.addView(a,lp);Button bt=Ui.button(this,"Autoriser le fonctionnement H24",true);bt.setOnClickListener(new View.OnClickListener(){public void onClick(View v){batteryReq();}});p.addView(bt,lp);l.addView(p,cardLp());LinearLayout alg=Ui.card(this);alg.addView(Ui.section(this,"MOTEUR SMART"));alg.addView(Ui.gap(this,7));alg.addView(pair("Trous en attente",String.valueOf(db.pendingCount()),db.pendingCount()>0?Ui.YELLOW:Ui.GREEN));Button rec=Ui.button(this,"Recalculer les trous maintenant",true);rec.setOnClickListener(new View.OnClickListener(){public void onClick(View v){if(!Net.internet(MainActivity.this))Toast.makeText(MainActivity.this,"Internet requis uniquement pour cette reconstruction",Toast.LENGTH_LONG).show();else{Reconstruction.kick(MainActivity.this);Toast.makeText(MainActivity.this,"Reconstruction lancée",Toast.LENGTH_SHORT).show();}});alg.addView(rec,lp);l.addView(alg,cardLp());return wrap(l);}

 void requestStart(){if(!perm(Manifest.permission.ACCESS_FINE_LOCATION)){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},REQ_LOC);return;}startTrack();}
 void startTrack(){getSharedPreferences("tracepilot",MODE_PRIVATE).edit().putBoolean("tracking_enabled",true).apply();Intent s=new Intent(this,TrackingService.class).setAction(TrackingService.START);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);Toast.makeText(this,"TracePilot H24 démarré",Toast.LENGTH_SHORT).show();}catch(Throwable t){getSharedPreferences("tracepilot",MODE_PRIVATE).edit().putBoolean("tracking_enabled",false).apply();new AlertDialog.Builder(this).setTitle("Démarrage refusé").setMessage(t.toString()).setPositiveButton("OK",null).show();}show("Live");}
 void stopTrack(){getSharedPreferences("tracepilot",MODE_PRIVATE).edit().putBoolean("tracking_enabled",false).apply();try{startService(new Intent(this,TrackingService.class).setAction(TrackingService.STOP));}catch(Throwable t){stopService(new Intent(this,TrackingService.class));}show("Live");}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_LOC){if(perm(Manifest.permission.ACCESS_FINE_LOCATION))startTrack();else Toast.makeText(this,"La localisation précise est nécessaire au suivi",Toast.LENGTH_LONG).show();}}
 boolean perm(String p){return Build.VERSION.SDK_INT<23||checkSelfPermission(p)==PackageManager.PERMISSION_GRANTED;}
 boolean battery(){try{PowerManager p=(PowerManager)getSystemService(POWER_SERVICE);return p!=null&&p.isIgnoringBatteryOptimizations(getPackageName());}catch(Throwable t){return false;}}
 void batteryReq(){try{startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())));}catch(Throwable t){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}
 void pick(){Calendar c=Calendar.getInstance();c.setTimeInMillis(day);new DatePickerDialog(this,new DatePickerDialog.OnDateSetListener(){public void onDateSet(DatePicker v,int y,int m,int d){Calendar x=Calendar.getInstance();x.set(y,m,d,0,0,0);x.set(Calendar.MILLISECOND,0);day=x.getTimeInMillis();show(page);}},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
 void point(TraceDb.Point p){String msg="Heure: "+date(p.ts)+" "+time(p.ts)+"\nCoordonnées: "+String.format(Locale.ROOT,"%.7f, %.7f",p.lat,p.lon)+"\nPrécision: "+p.acc+" m\nAltitude: "+p.alt+" m\nVitesse: "+String.format(Locale.ROOT,"%.2f km/h",p.speed*3.6)+"\nCap: "+p.bearing+"°\nProvider: "+p.provider+"\nSatellites: "+p.satsUsed+"/"+p.satsVisible+"\nInternet: "+(p.internet?"oui":"non")+"\nPression: "+p.pressure+" hPa\nAccel RMS: "+p.accel+"\nGyro RMS: "+p.gyro+"\nChamp mag.: "+p.mag+"\nPas: "+p.steps+"\n\nTransport: "+label(p.mode)+"\nConfiance: "+Math.round(p.confidence*100)+" %\nProbabilités: "+p.scores+"\nSource: "+p.source;new AlertDialog.Builder(this).setTitle("Point #"+p.id).setMessage(msg).setPositiveButton("OK",null).show();}
 static long dayStart(long t){Calendar c=Calendar.getInstance();c.setTimeInMillis(t);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
 static String time(long t){return new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(t));}static String date(long t){return new SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).format(new Date(t));}
 static String label(String m){if("walk".equals(m))return"Marche";if("run".equals(m))return"Course";if("bike".equals(m))return"Vélo";if("car".equals(m))return"Voiture";if("train".equals(m))return"Train";if("boat".equals(m))return"Bateau";if("air".equals(m))return"Avion";if("pending".equals(m))return"À reconstruire";return"Stationnaire";}
 static String duration(long ms){long s=Math.max(0,ms/1000),h=s/3600,m=(s%3600)/60;return h>0?h+"h "+m+"min":m+"min "+(s%60)+"s";}static String bytes(long b){double v=b;String[]u={"o","Ko","Mo","Go"};int i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return String.format(Locale.ROOT,i==0?"%.0f %s":"%.2f %s",v,u[i]);}
}
