package com.neo.tracepilot;

import android.content.Context;
import android.location.Location;
import org.json.JSONArray;import org.json.JSONObject;
import java.io.BufferedReader;import java.io.InputStreamReader;import java.net.HttpURLConnection;import java.net.URL;import java.util.List;import java.util.Locale;import java.util.concurrent.ExecutorService;import java.util.concurrent.Executors;import java.util.concurrent.atomic.AtomicBoolean;

final class Reconstruction{
 private static final ExecutorService EX=Executors.newSingleThreadExecutor();private static final AtomicBoolean BUSY=new AtomicBoolean(false);
 static void kick(Context c){final Context a=c.getApplicationContext();if(!Net.internet(a)||!BUSY.compareAndSet(false,true))return;EX.execute(new Runnable(){public void run(){TraceDb d=new TraceDb(a);try{List<TraceDb.Gap> gs=d.pending(10);for(TraceDb.Gap g:gs){if(!Net.internet(a))break;one(d,g);}}finally{d.close();BUSY.set(false);}}});}
 private static void one(TraceDb d,TraceDb.Gap g){double sec=Math.max(1,(g.endTs-g.startTs)/1000.0);float[]rr=new float[1];Location.distanceBetween(g.startLat,g.startLon,g.endLat,g.endLon,rr);double direct=rr[0],avg=direct/sec;if(avg>60||(direct>250000&&sec<18000)){d.updateGap(g.id,"reconstructed","air",.9,greatCircle(g,64),"Distance/temps typiques d'un vol; trajectoire grand cercle calculée après retour Internet.");return;}Road r=road(g,sec,direct);if(r!=null&&r.ok){d.updateGap(g.id,"reconstructed","car",Math.max(.62,.92-.25*r.err),r.path,"Route OSRM la plus cohérente avec la durée réelle du trou GPS.");return;}String mode=avg<2.5?"walk":avg>18?"train":"boat";double conf=avg<2.5?.62:avg>18?.58:.56;d.updateGap(g.id,"reconstructed",mode,conf,greatCircle(g,40),"Aucune route routière suffisamment cohérente; hypothèse cinématique marquée comme reconstruction.");}
 private static Road road(TraceDb.Gap g,double actual,double direct){HttpURLConnection c=null;try{String u=String.format(Locale.US,"https://router.project-osrm.org/route/v1/driving/%.6f,%.6f;%.6f,%.6f?overview=full&geometries=geojson&alternatives=true",g.startLon,g.startLat,g.endLon,g.endLat);c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("User-Agent","TracePilot/7.0 personal tracker");if(c.getResponseCode()!=200)return null;BufferedReader b=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String line;while((line=b.readLine())!=null)s.append(line);b.close();JSONObject root=new JSONObject(s.toString());JSONArray routes=root.optJSONArray("routes");if(routes==null)return null;Road best=null;for(int i=0;i<routes.length();i++){JSONObject ro=routes.getJSONObject(i);double dur=ro.optDouble("duration",Double.NaN),dist=ro.optDouble("distance",Double.NaN);JSONObject geo=ro.optJSONObject("geometry");JSONArray co=geo==null?null:geo.optJSONArray("coordinates");if(Double.isNaN(dur)||Double.isNaN(dist)||co==null)continue;double ratio=dur/Math.max(1,actual);double err=Math.abs(Math.log(Math.max(.01,ratio)));Road x=new Road();x.err=Math.min(1,err/1.5);x.ok=ratio>.22&&ratio<4.3&&dist/Math.max(50,direct)<5.5;x.path=coords(co);if(best==null||err<best.err)best=x;}return best;}catch(Throwable t){return null;}finally{if(c!=null)c.disconnect();}}
 private static String coords(JSONArray a)throws Exception{JSONArray out=new JSONArray();for(int i=0;i<a.length();i++){JSONArray q=a.getJSONArray(i),p=new JSONArray();p.put(q.getDouble(1));p.put(q.getDouble(0));out.put(p);}return out.toString();}
 private static String greatCircle(TraceDb.Gap g,int n){JSONArray out=new JSONArray();double p1=Math.toRadians(g.startLat),l1=Math.toRadians(g.startLon),p2=Math.toRadians(g.endLat),l2=Math.toRadians(g.endLon);double d=2*Math.asin(Math.sqrt(Math.pow(Math.sin((p2-p1)/2),2)+Math.cos(p1)*Math.cos(p2)*Math.pow(Math.sin((l2-l1)/2),2)));for(int i=0;i<n;i++){double f=i/(double)(n-1),lat,lon;if(d<1e-9){lat=g.startLat+(g.endLat-g.startLat)*f;lon=g.startLon+(g.endLon-g.startLon)*f;}else{double A=Math.sin((1-f)*d)/Math.sin(d),B=Math.sin(f*d)/Math.sin(d),x=A*Math.cos(p1)*Math.cos(l1)+B*Math.cos(p2)*Math.cos(l2),y=A*Math.cos(p1)*Math.sin(l1)+B*Math.cos(p2)*Math.sin(l2),z=A*Math.sin(p1)+B*Math.sin(p2);lat=Math.toDegrees(Math.atan2(z,Math.sqrt(x*x+y*y)));lon=Math.toDegrees(Math.atan2(y,x));}JSONArray q=new JSONArray();q.put(lat);q.put(lon);out.put(q);}return out.toString();}
 static final class Road{boolean ok;double err;String path;}
}
