package com.neo.tracepilot;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.hardware.*;import android.location.*;import android.os.*;import java.util.*;

public final class TrackingService extends Service implements LocationListener,SensorEventListener{
 static final String START="com.neo.tracepilot.START",STOP="com.neo.tracepilot.STOP";static final String CH="tracepilot_h24";static final int NID=701;static final long GAP=120000L;
 TraceDb db;LocationManager lm;SensorManager sm;Handler h=new Handler(Looper.getMainLooper());GnssStatus.Callback gc;TraceDb.Point last;long lastStore,stationarySince,lastStep,lastPressureTs;double pressure=Double.NaN,pressureRate,accel,gyro,mag,steps;int satsUsed,satsVisible;boolean lowRate;
 Runnable evidence=new Runnable(){public void run(){try{boolean net=Net.internet(TrackingService.this);db.addEvidence(System.currentTimeMillis(),pressure,accel,gyro,mag,steps,satsUsed,satsVisible,net);db.setMeta("internet",net?"1":"0");if(net&&db.pendingCount()>0)Reconstruction.kick(TrackingService.this);}catch(Throwable ignored){}h.postDelayed(this,60000);}};
 @Override public void onCreate(){super.onCreate();db=new TraceDb(this);lm=(LocationManager)getSystemService(LOCATION_SERVICE);sm=(SensorManager)getSystemService(SENSOR_SERVICE);last=db.last();channel();}
 @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null&&STOP.equals(i.getAction())){prefs(false);db.setMeta("service_state","stopped");stopSelf();return START_NOT_STICKY;}startForeground(NID,notif("Initialisation GPS…"));if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){prefs(false);db.setMeta("service_state","permission_missing");stopSelf();return START_NOT_STICKY;}prefs(true);db.setMeta("service_state","running");sensors();gnss();gps(true);h.removeCallbacks(evidence);h.post(evidence);return START_STICKY;}
 void prefs(boolean on){getSharedPreferences("tracepilot",MODE_PRIVATE).edit().putBoolean("tracking_enabled",on).apply();}
 void sensors(){if(sm==null)return;int[]t={Sensor.TYPE_ACCELEROMETER,Sensor.TYPE_GYROSCOPE,Sensor.TYPE_MAGNETIC_FIELD,Sensor.TYPE_PRESSURE,Sensor.TYPE_STEP_COUNTER,Sensor.TYPE_STEP_DETECTOR};for(int x:t)try{Sensor s=sm.getDefaultSensor(x);if(s!=null)sm.registerListener(this,s,SensorManager.SENSOR_DELAY_NORMAL);}catch(Throwable ignored){}}
 void gnss(){if(lm==null||Build.VERSION.SDK_INT<24)return;gc=new GnssStatus.Callback(){@Override public void onSatelliteStatusChanged(GnssStatus s){int v=s.getSatelliteCount(),u=0;for(int i=0;i<v;i++)if(s.usedInFix(i))u++;satsVisible=v;satsUsed=u;db.setMeta("sats_visible",String.valueOf(v));db.setMeta("sats_used",String.valueOf(u));}};try{lm.registerGnssStatusCallback(gc,h);}catch(Throwable ignored){}}
 void gps(boolean high){if(lm==null)return;try{lm.removeUpdates(this);}catch(Throwable ignored){}long t=high?3000:30000;float d=high?2:10;lowRate=!high;try{if(lm.isProviderEnabled(LocationManager.GPS_PROVIDER))lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,t,d,this,Looper.getMainLooper());}catch(Throwable e){db.setMeta("gps_error",e.getClass().getSimpleName());}try{if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,Math.max(10000,t),Math.max(5,d),this,Looper.getMainLooper());}catch(Throwable ignored){}db.setMeta("gps_rate",high?"high":"low");}
 @Override public void onLocationChanged(Location l){if(l==null)return;long now=System.currentTimeMillis();if(l.hasAccuracy()&&l.getAccuracy()>2000)return;if(last!=null&&now-lastStore<1800){float[]r=new float[1];Location.distanceBetween(last.lat,last.lon,l.getLatitude(),l.getLongitude(),r);if(r[0]<2.5)return;}double speed=l.hasSpeed()?Math.max(0,l.getSpeed()):calcSpeed(last,l,now);Classif c=classify(speed,accel,gyro,now-lastStep<90000,last==null?null:last.mode);TraceDb.Point p=new TraceDb.Point();p.ts=l.getTime()>0?l.getTime():now;p.lat=l.getLatitude();p.lon=l.getLongitude();p.acc=l.hasAccuracy()?l.getAccuracy():-1;p.alt=l.hasAltitude()?l.getAltitude():0;p.speed=speed;p.bearing=l.hasBearing()?l.getBearing():0;p.provider=l.getProvider()==null?"":l.getProvider();p.satsUsed=satsUsed;p.satsVisible=satsVisible;p.internet=Net.internet(this);p.pressure=pressure;p.accel=accel;p.gyro=gyro;p.mag=mag;p.steps=steps;p.mode=c.mode;p.confidence=c.conf;p.scores=c.scores;if(last!=null){long dt=p.ts-last.ts;float[]r=new float[1];Location.distanceBetween(last.lat,last.lon,p.lat,p.lon,r);if(dt>GAP&&r[0]>30)db.addGap(last,p);}db.addPoint(p);last=p;lastStore=now;status(p);rate(p);if(p.internet&&db.pendingCount()>0)Reconstruction.kick(this);NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null)nm.notify(NID,notif(label(p.mode)+" • "+String.format(Locale.ROOT,"%.1f km/h",p.speed*3.6)+" • ±"+Math.round(p.acc)+" m"));}
 double calcSpeed(TraceDb.Point a,Location b,long now){if(a==null)return 0;long dt=Math.max(1000,(b.getTime()>0?b.getTime():now)-a.ts);float[]r=new float[1];Location.distanceBetween(a.lat,a.lon,b.getLatitude(),b.getLongitude(),r);return r[0]/(dt/1000.0);}
 void status(TraceDb.Point p){db.setMeta("last_fix_ts",String.valueOf(p.ts));db.setMeta("last_lat",String.valueOf(p.lat));db.setMeta("last_lon",String.valueOf(p.lon));db.setMeta("last_acc",String.valueOf(p.acc));db.setMeta("last_speed",String.valueOf(p.speed));db.setMeta("last_mode",p.mode);db.setMeta("last_conf",String.valueOf(p.confidence));db.setMeta("internet",p.internet?"1":"0");}
 void rate(TraceDb.Point p){long n=System.currentTimeMillis();boolean still=p.speed<.65&&accel<.17;if(still){if(stationarySince==0)stationarySince=n;if(!lowRate&&n-stationarySince>300000)gps(false);}else{stationarySince=0;if(lowRate)gps(true);}}
 @Override public void onSensorChanged(SensorEvent e){if(e==null||e.sensor==null)return;int t=e.sensor.getType();long n=System.currentTimeMillis();if(t==Sensor.TYPE_ACCELEROMETER&&e.values.length>=3){double m=Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]),d=Math.abs(m-SensorManager.GRAVITY_EARTH);accel=.9*accel+.1*d;if(lowRate&&d>.45){stationarySince=0;gps(true);}}else if(t==Sensor.TYPE_GYROSCOPE&&e.values.length>=3){double m=Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]);gyro=.9*gyro+.1*m;}else if(t==Sensor.TYPE_MAGNETIC_FIELD&&e.values.length>=3)mag=Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]);else if(t==Sensor.TYPE_PRESSURE&&e.values.length>0){double np=e.values[0];if(!Double.isNaN(pressure)&&lastPressureTs>0){double min=(n-lastPressureTs)/60000.0;if(min>.03)pressureRate=(np-pressure)/min;}pressure=np;lastPressureTs=n;}else if(t==Sensor.TYPE_STEP_COUNTER&&e.values.length>0){if(e.values[0]>steps)lastStep=n;steps=e.values[0];}else if(t==Sensor.TYPE_STEP_DETECTOR)lastStep=n;}
 @Override public void onAccuracyChanged(Sensor s,int a){}@Override public void onProviderEnabled(String p){}@Override public void onProviderDisabled(String p){db.setMeta("provider_disabled",p);}@SuppressWarnings("deprecation")@Override public void onStatusChanged(String p,int s,Bundle b){}
 static final class Classif{String mode,scores;double conf;Classif(String m,double c,String s){mode=m;conf=c;scores=s;}}
 Classif classify(double v,double a,double g,boolean stepsNow,String prev){String[]m={"stationary","walk","run","bike","car","train","boat","air"};double[]s={gauss(v,0,.55)*2.4,gauss(v,1.35,.85)*(stepsNow?3:.45),gauss(v,3.1,1.5)*(stepsNow?2.4:.5),gauss(v,6.5,4.2)*(stepsNow?.65:1.2),gauss(v,18,14)*1.35,gauss(v,34,20)*(g<.16?1.7:1)*(a<.55?1.4:1),gauss(v,8,7)*(g<.2?1.35:1)*(a<.45?1.25:1),gauss(v,210,130)};if(v>70)s[7]+=5;if(v>45&&g<.12)s[5]+=1.2;if(v<.7&&a<.16)s[0]+=3;if(stepsNow&&v<2.3)s[1]+=2;if(prev!=null)for(int i=0;i<m.length;i++)if(m[i].equals(prev))s[i]=s[i]*1.55+.15;double tot=0;for(double x:s)tot+=Math.max(.0001,x);int bi=0;double bp=0;StringBuilder js=new StringBuilder("{");for(int i=0;i<m.length;i++){double p=Math.max(.0001,s[i])/tot;if(p>bp){bp=p;bi=i;}if(i>0)js.append(',');js.append('"').append(m[i]).append("\":").append(String.format(Locale.ROOT,"%.3f",p));}js.append('}');return new Classif(m[bi],bp,js.toString());}
 double gauss(double x,double mu,double sig){double z=(x-mu)/sig;return Math.exp(-.5*z*z)+.01;}
 void channel(){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(n!=null)n.createNotificationChannel(new NotificationChannel(CH,"TracePilot H24",NotificationManager.IMPORTANCE_LOW));}}
 Notification notif(String text){Intent o=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,1,o,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));Intent st=new Intent(this,TrackingService.class).setAction(STOP);PendingIntent ps=PendingIntent.getService(this,2,st,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CH):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.ic_menu_mylocation).setContentTitle("TracePilot H24 actif").setContentText(text).setContentIntent(pi).setOngoing(true).addAction(new Notification.Action.Builder(android.R.drawable.ic_delete,"Arrêter",ps).build()).build();}
 static String label(String m){if("walk".equals(m))return"Marche";if("run".equals(m))return"Course";if("bike".equals(m))return"Vélo";if("car".equals(m))return"Voiture";if("train".equals(m))return"Train";if("boat".equals(m))return"Bateau";if("air".equals(m))return"Avion";return"Stationnaire";}
 @Override public void onDestroy(){h.removeCallbacksAndMessages(null);try{if(lm!=null)lm.removeUpdates(this);}catch(Throwable ignored){}try{if(Build.VERSION.SDK_INT>=24&&lm!=null&&gc!=null)lm.unregisterGnssStatusCallback(gc);}catch(Throwable ignored){}try{if(sm!=null)sm.unregisterListener(this);}catch(Throwable ignored){}if(db!=null)db.close();super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
}
