plugins { id 'com.android.application' }

android {
    namespace 'com.neo.aircontrol'
    compileSdk 35
    defaultConfig {
        applicationId 'com.neo.aircontrol'
        minSdk 26
        targetSdk 35
        versionCode 14
        versionName '7.4-stable-pointer-volume-fix'
    }
}

dependencies {
    implementation 'com.google.mediapipe:tasks-vision:latest.release'
}
