plugins { id 'com.android.application' }

android {
    namespace 'com.neo.aircontrol'
    compileSdk 35
    defaultConfig {
        applicationId 'com.neo.aircontrol'
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName '6.1-v5feel'
    }
}

dependencies {
    implementation 'com.google.mediapipe:tasks-vision:latest.release'
}
