package com.sentry.local;

import android.Manifest;import android.app.AlertDialog;import android.content.Intent;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.opengl.GLES11Ext;import android.opengl.GLES20;import android.opengl.GLSurfaceView;import android.os.Bundle;import android.provider.Settings;import android.view.Gravity;import android.view.View;import android.view.WindowManager;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.ProgressBar;import android.widget.TextView;import android.widget.Toast;
import com.google.ar.core.*;import org.json.JSONArray;import org.json.JSONObject;import java.nio.*;import java.util.*;

public class AutoSpatialScanActivity extends android.app.Activity implements GLSurfaceView.Renderer {
 private static final int REQ=2502; private GLSurfaceView gl; private Session session; private Bg bg; private boolean resumed,install; private int w,h,frames; private float minX=999,maxX=-999,minZ=999,maxZ=-999,floor=999,ceiling=-999; private TextView state,tip,button; private ProgressBar progress; private long lastSample; private final Set<String> planes=new HashSet<>();
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_SECURE);build();if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},REQ);}
 private void build(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);gl=new GLSurfaceView(this);gl.setEGLContextClientVersion(2);gl.setEGLConfigChooser(8,8,8,8,16,0);gl.setRenderer(this);root.addView(gl,new FrameLayout.LayoutParams(-1,-1));LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(dp(16),dp(18),dp(16),dp(16));top.setBackground(round(Color.argb(225,3,14,20),0));top.addView(t("SCAN AUTO 3D",23,Color.WHITE,true));top.addView(space(8));state=t("CALIBRATION · 0 %",13,Color.rgb(61,235,211),true);tip=t("Marche lentement le long des murs et montre le sol, les murs puis le plafond.",12,Color.LTGRAY,false);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);top.addView(state);top.addView(space(6));top.addView(progress);top.addView(space(8));top.addView(tip);root.addView(top,new FrameLayout.LayoutParams(-1,-2,Gravity.TOP));LinearLayout bot=new LinearLayout(this);bot.setOrientation(LinearLayout.VERTICAL);bot.setPadding(dp(14),dp(12),dp(14),dp(14));bot.setBackground(round(Color.argb(235,4,18,25),22));button=t("TERMINER ET CRÉER LE MODÈLE",13,Color.rgb(2,24,22),true);button.setGravity(Gravity.CENTER);button.setPadding(dp(12),dp(15),dp(12),dp(15));button.setBackground(round(Color.rgb(61,235,211),16));button.setEnabled(false);button.setAlpha(.45f);button.setOnClickListener(v->finishScan());TextView manual=t("PASSER AU MODE MANUEL",11,Color.WHITE,true);manual.setGravity(Gravity.CENTER);manual.setPadding(0,dp(14),0,dp(8));manual.setOnClickListener(v->{startActivity(new Intent(this,SpatialScanActivity.class));finish();});bot.addView(button);bot.addView(manual);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);lp.setMargins(dp(10),0,dp(10),dp(10));root.addView(bot,lp);setContentView(root);}
 @Override protected void onResume(){super.onResume();if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)return;if(!ensure())return;try{session.resume();resumed=true;gl.onResume();}catch(Exception e){fatal("Caméra indisponible");}}
 @Override protected void onPause(){resumed=false;if(gl!=null)gl.onPause();if(session!=null)session.pause();super.onPause();}
 @Override protected void onDestroy(){if(session!=null)session.close();super.onDestroy();}
 private boolean ensure(){if(session!=null)return true;try{if(ArCoreApk.getInstance().requestInstall(this,!install)==ArCoreApk.InstallStatus.INSTALL_REQUESTED){install=true;return false;}session=new Session(this);Config c=session.getConfig();c.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL_AND_VERTICAL);if(session.isDepthModeSupported(Config.DepthMode.AUTOMATIC))c.setDepthMode(Config.DepthMode.AUTOMATIC);c.setUpdateMode(Config.UpdateMode.LATEST_CAMERA_IMAGE);session.configure(c);return true;}catch(Exception e){fatal("ARCore indisponible : "+e.getClass().getSimpleName());return false;}}
 @Override public void onSurfaceCreated(javax.microedition.khronos.opengles.GL10 x,javax.microedition.khronos.egl.EGLConfig c){bg=new Bg();bg.create();if(session!=null)session.setCameraTextureName(bg.tex);}
 @Override public void onSurfaceChanged(javax.microedition.khronos.opengles.GL10 x,int a,int b){w=a;h=b;GLES20.glViewport(0,0,a,b);geometry();}
 @Override public void onDrawFrame(javax.microedition.khronos.opengles.GL10 x){GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);if(session==null||!resumed||bg==null)return;try{session.setCameraTextureName(bg.tex);geometry();Frame f=session.update();bg.draw(f);if(f.getCamera().getTrackingState()!=TrackingState.TRACKING)return;frames++;Pose p=f.getCamera().getPose();long now=System.currentTimeMillis();if(now-lastSample>180){lastSample=now;float px=p.tx(),pz=p.tz();minX=Math.min(minX,px);maxX=Math.max(maxX,px);minZ=Math.min(minZ,pz);maxZ=Math.max(maxZ,pz);for(Plane pl:session.getAllTrackables(Plane.class)){if(pl.getTrackingState()!=TrackingState.TRACKING||pl.getSubsumedBy()!=null)continue;planes.add(pl.getType()+":"+Math.round(pl.getCenterPose().tx()*10)+":"+Math.round(pl.getCenterPose().tz()*10));if(pl.getType()==Plane.Type.HORIZONTAL_UPWARD_FACING)floor=Math.min(floor,pl.getCenterPose().ty());if(pl.getType()==Plane.Type.HORIZONTAL_DOWNWARD_FACING)ceiling=Math.max(ceiling,pl.getCenterPose().ty());}runOnUiThread(this::updateUi);}}catch(Exception ignored){}}
 private void geometry(){if(session!=null&&w>0&&h>0)session.setDisplayGeometry(getWindowManager().getDefaultDisplay().getRotation(),w,h);}
 private void updateUi(){float dx=maxX-minX,dz=maxZ-minZ,motion=Math.max(0,dx)+Math.max(0,dz);int score=Math.min(100,Math.min(45,planes.size()*5)+Math.min(40,(int)(motion*12))+Math.min(15,frames/25));progress.setProgress(score);String phase=score<25?"CALIBRATION":score<65?"DÉTECTION DES SURFACES":score<85?"FERMETURE DE LA PIÈCE":"PRÊT";state.setText(phase+" · "+score+" %");if(score<25)tip.setText("Bouge doucement de gauche à droite pour stabiliser le suivi.");else if(score<65)tip.setText("Fais le tour de la pièce. Montre chaque mur du sol au plafond.");else if(score<85)tip.setText("Reviens vers ton point de départ et montre les zones manquantes.");else tip.setText("Couverture suffisante. Tu peux créer le modèle 3D.");boolean ready=score>=72&&dx>.7f&&dz>.7f;button.setEnabled(ready);button.setAlpha(ready?1f:.45f);}
 private void finishScan(){float dx=Math.max(1.2f,maxX-minX+1.6f),dz=Math.max(1.2f,maxZ-minZ+1.6f),cx=(minX+maxX)/2f,cz=(minZ+maxZ)/2f,fy=floor<900?floor:0f,height=(ceiling>-900&&floor<900&&ceiling-floor>1.6f)?ceiling-floor:2.5f;try{JSONArray pts=new JSONArray();pts.put(new JSONArray().put(cx-dx/2).put(fy).put(cz-dz/2));pts.put(new JSONArray().put(cx+dx/2).put(fy).put(cz-dz/2));pts.put(new JSONArray().put(cx+dx/2).put(fy).put(cz+dz/2));pts.put(new JSONArray().put(cx-dx/2).put(fy).put(cz+dz/2));JSONObject o=new JSONObject();o.put("time",System.currentTimeMillis());o.put("shape","Pièce automatique approximée");o.put("area_m2",dx*dz);o.put("perimeter_m",2*(dx+dz));o.put("height_m",height);o.put("volume_m3",dx*dz*height);o.put("confidence",Math.min(91,55+planes.size()*3));o.put("auto",true);o.put("floor_points",pts);getSharedPreferences("sentry_spatial_scans",MODE_PRIVATE).edit().putString("latest",o.toString()).putLong("latest_time",System.currentTimeMillis()).apply();startActivity(new Intent(this,RoomModelActivity.class));finish();}catch(Exception e){Toast.makeText(this,"Création impossible",Toast.LENGTH_SHORT).show();}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)onResume();else new AlertDialog.Builder(this).setTitle("Caméra requise").setMessage("Le scan automatique utilise la caméra et ARCore.").setPositiveButton("Réglages",(d,x)->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,android.net.Uri.parse("package:"+getPackageName())))).setNegativeButton("Fermer",(d,x)->finish()).show();}
 private void fatal(String s){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Scanner indisponible").setMessage(s).setPositiveButton("Fermer",(d,x)->finish()).show());}
 private TextView t(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);return v;}private View space(int x){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,dp(x)));return v;}private GradientDrawable round(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}private int dp(float x){return Math.round(x*getResources().getDisplayMetrics().density);}
 private static final class Bg{int tex,prog,pos,uv,uni;FloatBuffer verts=b(new float[]{-1,-1,1,-1,-1,1,1,1}),out=b(new float[8]),ndc=b(new float[]{-1,-1,1,-1,-1,1,1,1});void create(){int[] t=new int[1];GLES20.glGenTextures(1,t,0);tex=t[0];GLES20.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,tex);GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,GLES20.GL_TEXTURE_MIN_FILTER,GLES20.GL_LINEAR);GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,GLES20.GL_TEXTURE_MAG_FILTER,GLES20.GL_LINEAR);GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,GLES20.GL_TEXTURE_WRAP_S,GLES20.GL_CLAMP_TO_EDGE);GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,GLES20.GL_TEXTURE_WRAP_T,GLES20.GL_CLAMP_TO_EDGE);prog=link("attribute vec4 a;attribute vec2 u;varying vec2 v;void main(){gl_Position=a;v=u;}","#extension GL_OES_EGL_image_external : require\nprecision mediump float;uniform samplerExternalOES s;varying vec2 v;void main(){gl_FragColor=texture2D(s,v);}");pos=GLES20.glGetAttribLocation(prog,"a");uv=GLES20.glGetAttribLocation(prog,"u");uni=GLES20.glGetUniformLocation(prog,"s");}void draw(Frame f){ndc.position(0);out.position(0);f.transformCoordinates2d(Coordinates2d.OPENGL_NORMALIZED_DEVICE_COORDINATES,ndc,Coordinates2d.TEXTURE_NORMALIZED,out);GLES20.glUseProgram(prog);verts.position(0);GLES20.glVertexAttribPointer(pos,2,GLES20.GL_FLOAT,false,0,verts);GLES20.glEnableVertexAttribArray(pos);out.position(0);GLES20.glVertexAttribPointer(uv,2,GLES20.GL_FLOAT,false,0,out);GLES20.glEnableVertexAttribArray(uv);GLES20.glActiveTexture(GLES20.GL_TEXTURE0);GLES20.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,tex);GLES20.glUniform1i(uni,0);GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP,0,4);}static FloatBuffer b(float[] x){FloatBuffer f=ByteBuffer.allocateDirect(x.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();f.put(x).position(0);return f;}static int sh(int t,String s){int x=GLES20.glCreateShader(t);GLES20.glShaderSource(x,s);GLES20.glCompileShader(x);return x;}static int link(String v,String f){int p=GLES20.glCreateProgram();GLES20.glAttachShader(p,sh(GLES20.GL_VERTEX_SHADER,v));GLES20.glAttachShader(p,sh(GLES20.GL_FRAGMENT_SHADER,f));GLES20.glLinkProgram(p);return p;}}
}
