name: SpeedSMP
version: '1.0.5-pvp'
main: fr.neo.speedsmp.SpeedSmpPlugin
api-version: '1.21.11'
author: Neo
description: SpeedSMP - fragments uniquement lors des kills par un joueur.
commands:
  speed:
    usage: /speed
  speeditem:
    usage: /speeditem [joueur] [quantite]
  withdraw:
    description: Transforme ta Speed permanente en fragments.
    usage: /withdraw [quantite]
permissions:
  speedsmp.admin:
    default: op
