package com.neo.aircontrol;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.SurfaceTexture;import android.hardware.Camera;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.IOException;import java.util.List;

@SuppressWarnings("deprecation")
public final class AirControlService extends Service implements Camera.PreviewCallback {
 public static final String ACTION_STOP="com.neo.aircontrol.STOP",ACTION_CALIBRATE="com.neo.aircontrol.CALIBRATE"; private static final String CHANNEL="aircontrol_camera";
 private Camera camera;private int fw,fh,camRot;private SurfaceTexture tex;private WindowManager wm;private LinearLayout panel;private TextView bubble,status;private WindowManager.LayoutParams params;private final MotionGestureDetector detector=new MotionGestureDetector();private volatile boolean calibrateNext;private long lastUi,fpsStart;private int fpsFrames;private float fps;
 @Override public void onCreate(){super.onCreate();channel();startForeground(42,notification("AirControl V2 actif - camera locale"));startCamera();if(Settings.canDrawOverlays(this))showOverlay();}
 @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null){if(ACTION_STOP.equals(i.getAction())){stopSelf();return START_NOT_STICKY;}if(ACTION_CALIBRATE.equals(i.getAction()))calibrateNext=true;}return START_STICKY;}
 private void channel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"AirControl camera",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private Notification notification(String text){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,1,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);return b.setSmallIcon(android.R.drawable.ic_menu_camera).setContentTitle("AirControl V2").setContentText(text).setOngoing(true).setContentIntent(pi).build();}
 private int front(){Camera.CameraInfo info=new Camera.CameraInfo();for(int i=0;i<Camera.getNumberOfCameras();i++){Camera.getCameraInfo(i,info);if(info.facing==Camera.CameraInfo.CAMERA_FACING_FRONT)return i;}return-1;}
 private int deg(int r){switch(r){case Surface.ROTATION_90:return 90;case Surface.ROTATION_180:return 180;case Surface.ROTATION_270:return 270;default:return 0;}}
 private void startCamera(){int id=front();if(id<0){stopSelf();return;}try{Camera.CameraInfo info=new Camera.CameraInfo();Camera.getCameraInfo(id,info);int device=deg(((WindowManager)getSystemService(WINDOW_SERVICE)).getDefaultDisplay().getRotation());int relative=(info.orientation-device+360)%360;camRot=(360-relative)%360;detector.setFrameTransform(camRot,true);camera=Camera.open(id);Camera.Parameters p=camera.getParameters();Camera.Size chosen=null;for(Camera.Size s:p.getSupportedPreviewSizes())if(chosen==null||Math.abs(s.width-640)+Math.abs(s.height-480)<Math.abs(chosen.width-640)+Math.abs(chosen.height-480))chosen=s;if(chosen!=null)p.setPreviewSize(chosen.width,chosen.height);p.setPreviewFormat(android.graphics.ImageFormat.NV21);List<String> fm=p.getSupportedFocusModes();if(fm!=null&&fm.contains(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO))p.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO);camera.setParameters(p);Camera.Size a=camera.getParameters().getPreviewSize();fw=a.width;fh=a.height;tex=new SurfaceTexture(0);camera.setPreviewTexture(tex);camera.setPreviewCallback(this);camera.startPreview();calibrateNext=true;fpsStart=SystemClock.elapsedRealtime();}catch(RuntimeException|IOException e){stopSelf();}}
 @Override public void onPreviewFrame(byte[] data,Camera c){if(data==null||fw<=0)return;long now=SystemClock.elapsedRealtime();fpsFrames++;if(now-fpsStart>=1000){fps=fpsFrames*1000f/Math.max(1,now-fpsStart);fpsFrames=0;fpsStart=now;}if(calibrateNext){detector.beginCalibration();calibrateNext=false;}GestureCommand cmd=detector.process(data,fw,fh,now);if(cmd!=GestureCommand.NONE){boolean ok=AirAccessibilityService.perform(cmd);bubbleState(3);setStatus((ok?"GESTE ":"ACCESSIBILITE OFF - ")+cmd.name());return;}if(now-lastUi>180){MotionGestureDetector.DebugState d=detector.debug();String s;int state;if(d.calibrating){s="Calibration "+d.calibrationFrame+"/14\nRetire ta main";state=0;}else if(!d.handFound){s=String.format(java.util.Locale.US,"CAM %.0f fps | rot %d\nPas de main | FG %.1f%% | peau %.1f%%",fps,camRot,d.foregroundRatio*100f,d.skinRatio*100f);state=0;}else if(d.armed){s=String.format(java.util.Locale.US,"ARME - fais ton swipe\nmain %.1f%% | pics %d",d.areaRatio*100f,d.peaks);state=3;}else if(d.twoFingerGate){s=String.format(java.util.Locale.US,"V DETECTE %d/3\nmain %.1f%% | pics %d",d.gateFrames,d.areaRatio*100f,d.peaks);state=2;}else{s=String.format(java.util.Locale.US,"MAIN OK - montre V\nmain %.1f%% | pics %d | FG %.1f%%",d.areaRatio*100f,d.peaks,d.foregroundRatio*100f);state=1;}bubbleState(state);setStatus(s);}}
 private void showOverlay(){wm=(WindowManager)getSystemService(WINDOW_SERVICE);params=new WindowManager.LayoutParams(WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);params.gravity=Gravity.TOP|Gravity.END;params.x=6;params.y=180;panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(8),dp(8),dp(8),dp(8));panel.setBackgroundColor(0xE6111318);bubble=new TextView(this);bubble.setText("AC\nV2");bubble.setTextColor(Color.WHITE);bubble.setTextSize(13);bubble.setGravity(Gravity.CENTER);bubble.setBackgroundColor(0xFF343840);panel.addView(bubble,new LinearLayout.LayoutParams(dp(52),dp(52)));status=new TextView(this);status.setText("AirControl V2 ON");status.setTextColor(Color.WHITE);status.setTextSize(12);status.setPadding(0,dp(7),0,dp(5));status.setVisibility(View.GONE);panel.addView(status,new LinearLayout.LayoutParams(dp(255),-2));Button cal=new Button(this);cal.setText("Recalibrer fond");cal.setVisibility(View.GONE);panel.addView(cal,new LinearLayout.LayoutParams(dp(255),dp(46)));Button test=new Button(this);test.setText("Test swipe bas");test.setVisibility(View.GONE);panel.addView(test,new LinearLayout.LayoutParams(dp(255),dp(46)));Button off=new Button(this);off.setText("OFF");off.setVisibility(View.GONE);panel.addView(off,new LinearLayout.LayoutParams(dp(255),dp(46)));bubble.setOnClickListener(v->{boolean o=status.getVisibility()!=View.VISIBLE;status.setVisibility(o?View.VISIBLE:View.GONE);cal.setVisibility(o?View.VISIBLE:View.GONE);test.setVisibility(o?View.VISIBLE:View.GONE);off.setVisibility(o?View.VISIBLE:View.GONE);});cal.setOnClickListener(v->{calibrateNext=true;setStatus("Retire ta main pendant la calibration...");});test.setOnClickListener(v->{boolean ok=AirAccessibilityService.perform(GestureCommand.DOWN);setStatus(ok?"Test DOWN envoye":"Accessibilite inactive");});off.setOnClickListener(v->stopSelf());wm.addView(panel,params);}
 private void bubbleState(int s){if(bubble==null)return;final int bg;final String t;switch(s){case 1:bg=0xFF725B20;t="AC\nH";break;case 2:bg=0xFF176B77;t="AC\nV";break;case 3:bg=0xFF246B3B;t="AC\nGO";break;default:bg=0xFF343840;t="AC\nV2";}bubble.post(()->{bubble.setText(t);bubble.setBackgroundColor(bg);});}
 private void setStatus(String s){lastUi=SystemClock.elapsedRealtime();if(status!=null)status.post(()->status.setText(s));}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 @Override public void onDestroy(){if(camera!=null){try{camera.setPreviewCallback(null);camera.stopPreview();camera.release();}catch(Exception ignored){}camera=null;}if(tex!=null)tex.release();if(wm!=null&&panel!=null)try{wm.removeView(panel);}catch(Exception ignored){}stopForeground(true);super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
}
